name: Latex-multicompiler

on:
  push:
    branches:
      - 'master'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository contents
      uses: actions/checkout@v1

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
          root_file: ch2/main.tex
    - uses: actions/upload-artifact@v1
      with:
        name: testing
        path: ch2/main.pdf
