name: Latex-multicompiler

on:
  push:
    branches:
      - 'master'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository contents
      uses: actions/checkout@v1
    - name: get changed files
      run: |
      git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep "tex" 
      shell: bash

