name: Latex-multicompiler

on:
  push:
    branches:
      - 'master'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository contents
      uses: actions/checkout@v1
    - name: get changed files
      id: getfile
      run: |
          name=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '.*.tex') && echo $name && echo $name > listtocompile
    - name: Latex compiler
      uses: Jatus93/Latex-multicompiler@master
      with:
        path_to_list: listtocompile
        artifact: true
