name: Latex-multicompiler

on:
  push:
    branches:
      - 'master'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository contents
      uses: actions/checkout@v1

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
          root_file: ch2/main.tex
    - name: send photo message
      uses: appleboy/telegram-action@master
      with:
        to: @AlfredoBbot
        token: 656002531:AAFOoW2RvD8n-9Xtd03GbNPcaGqZ4f1JBeU
        message: send photo message
        document: ch2/main.pdf
