name: Latex-multicompiler

on:
  push:
    branches:
      - 'master'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository contents
      uses: actions/checkout@v1
    - name: get changed files
      run: echo 'git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | sed "/tex/!d" | sed "s/\/[^\/]*$//g" > listtocompile' | bash
    - name: doit
      run: cat listtocompile
    - name: Latex compiler
      uses: Jatus93/Latex-multicompiler@master
      with:
        path_to_list: listtocompile
        artifact: true
    - uses: actions/upload-artifact@v1
      with:
        name: Documents.tar.gz
        path: Documents